#!/usr/bin/env node
/**
 * Validate PyArrow-generated BinaryView/Utf8View test data using arrow-js.
 *
 * This script demonstrates cross-implementation compatibility by reading
 * Arrow IPC files created by PyArrow and validating their contents.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Table, tableFromIPC } from '../../targets/es2015/cjs/Arrow.node.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const testFiles = [
  'binaryview_test.arrow',
  'utf8view_test.arrow',
  'combined_test.arrow'
];

let allTestsPassed = true;

console.log('='.repeat(60));
console.log('BinaryView/Utf8View Integration Test Validation');
console.log('='.repeat(60));
console.log();

for (const filename of testFiles) {
  const filepath = path.join(__dirname, filename);

  console.log(`Testing: ${filename}`);
  console.log('-'.repeat(60));

  try {
    // Read the Arrow IPC file
    const buffer = fs.readFileSync(filepath);
    const table = tableFromIPC(buffer);

    console.log(`✓ Successfully opened file`);
    console.log(`  Schema: ${table.schema.fields.map(f => `${f.name}: ${f.type}`).join(', ')}`);
    console.log(`  Rows: ${table.numRows}`);
    console.log(`  Columns: ${table.numCols}`);

    // Validate we can read all values
    let nullCount = 0;
    let emptyCount = 0;
    let inlineCount = 0;
    let outOfLineCount = 0;
    let validationError = null;

    for (let i = 0; i < table.numRows; i++) {
      for (let col = 0; col < table.numCols; col++) {
        const value = table.getChildAt(col).get(i);
        const colType = table.schema.fields[col].type.toString();

        // For Utf8View, validate that we can decode the value
        if (colType.includes('Utf8View') && value !== null && value.length > 0) {
          try {
            if (value instanceof Uint8Array) {
              new TextDecoder().decode(value);
            } else {
              // Should be a string - validate it's valid
              String(value);
            }
          } catch (e) {
            validationError = `Failed to decode Utf8View value at row ${i}, col ${col}: ${e.message}`;
            break;
          }
        }

        if (value === null) {
          nullCount++;
        } else if (value.length === 0) {
          emptyCount++;
        } else if (value.length <= 12) {
          inlineCount++;
        } else {
          outOfLineCount++;
        }
      }
      if (validationError) break;
    }

    if (validationError) {
      throw new Error(validationError);
    }

    console.log(`  Values read: ${table.numRows * table.numCols}`);
    console.log(`    - Null values: ${nullCount}`);
    console.log(`    - Empty values: ${emptyCount}`);
    console.log(`    - Inline (≤12 bytes): ${inlineCount}`);
    console.log(`    - Out-of-line (>12 bytes): ${outOfLineCount}`);

    // Display sample values
    console.log(`  Sample values:`);
    for (let i = 0; i < Math.min(3, table.numRows); i++) {
      const values = [];
      for (let col = 0; col < table.numCols; col++) {
        const value = table.getChildAt(col).get(i);
        if (value === null) {
          values.push('null');
        } else if (value.length === 0) {
          values.push('""');
        } else {
          // For binary data, show hex preview; for strings, show text
          const colType = table.schema.fields[col].type.toString();
          if (colType.includes('Utf8View')) {
            // Utf8View values are already validated above, safe to decode
            const str = value instanceof Uint8Array
              ? new TextDecoder().decode(value)
              : String(value);
            const preview = str.length > 30 ? str.slice(0, 30) + '...' : str;
            values.push(`"${preview}"`);
          } else {
            const hex = Array.from(value.slice(0, 10))
              .map(b => b.toString(16).padStart(2, '0'))
              .join('');
            const preview = value.length > 10 ? hex + '...' : hex;
            values.push(`0x${preview}`);
          }
        }
      }
      console.log(`    Row ${i}: ${values.join(', ')}`);
    }

    console.log(`✓ All values successfully read and validated`);
    console.log();

  } catch (error) {
    console.error(`✗ Failed to validate ${filename}`);
    console.error(`  Error: ${error.message}`);
    console.error();
    allTestsPassed = false;
  }
}

console.log('='.repeat(60));
if (allTestsPassed) {
  console.log('✓ All integration tests passed!');
  console.log();
  console.log('This demonstrates that arrow-js can successfully read');
  console.log('BinaryView and Utf8View data generated by PyArrow,');
  console.log('proving cross-implementation compatibility.');
  process.exit(0);
} else {
  console.log('✗ Some tests failed');
  process.exit(1);
}
console.log('='.repeat(60));
